/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationIndexRouteImport } from './routes/simulation.index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios.index'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as SimulationIdRouteImport } from './routes/simulation.$id'
import { Route as ScenariosIdRouteImport } from './routes/scenarios.$id'
import { Route as ReportIdRouteImport } from './routes/report.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationIndexRoute = SimulationIndexRouteImport.update({
  id: '/simulation/',
  path: '/simulation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationIdRoute = SimulationIdRouteImport.update({
  id: '/simulation/$id',
  path: '/simulation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIdRoute = ScenariosIdRouteImport.update({
  id: '/scenarios/$id',
  path: '/scenarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/simulation/$id': typeof SimulationIdRoute
  '/report/': typeof ReportIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/simulation/': typeof SimulationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/simulation/$id': typeof SimulationIdRoute
  '/report': typeof ReportIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/simulation': typeof SimulationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report/$id': typeof ReportIdRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/simulation/$id': typeof SimulationIdRoute
  '/report/': typeof ReportIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/simulation/': typeof SimulationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report/$id'
    | '/scenarios/$id'
    | '/simulation/$id'
    | '/report/'
    | '/scenarios/'
    | '/simulation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report/$id'
    | '/scenarios/$id'
    | '/simulation/$id'
    | '/report'
    | '/scenarios'
    | '/simulation'
  id:
    | '__root__'
    | '/'
    | '/report/$id'
    | '/scenarios/$id'
    | '/simulation/$id'
    | '/report/'
    | '/scenarios/'
    | '/simulation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportIdRoute: typeof ReportIdRoute
  ScenariosIdRoute: typeof ScenariosIdRoute
  SimulationIdRoute: typeof SimulationIdRoute
  ReportIndexRoute: typeof ReportIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  SimulationIndexRoute: typeof SimulationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/': {
      id: '/simulation/'
      path: '/simulation'
      fullPath: '/simulation/'
      preLoaderRoute: typeof SimulationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$id': {
      id: '/simulation/$id'
      path: '/simulation/$id'
      fullPath: '/simulation/$id'
      preLoaderRoute: typeof SimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$id': {
      id: '/scenarios/$id'
      path: '/scenarios/$id'
      fullPath: '/scenarios/$id'
      preLoaderRoute: typeof ScenariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportIdRoute: ReportIdRoute,
  ScenariosIdRoute: ScenariosIdRoute,
  SimulationIdRoute: SimulationIdRoute,
  ReportIndexRoute: ReportIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  SimulationIndexRoute: SimulationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
